FROM python:3.10-slim

RUN pip install --no-cache-dir mlflow==2.15.1 boto3==1.34.162
WORKDIR /mlflow
EXPOSE 5000

CMD ["mlflow", "server", "--host=0.0.0.0", "--port=5000", "--backend-store-uri", "sqlite:///mlflow.db", "--default-artifact-root", "s3://mlflow"]
