FROM python:3.10-slim

WORKDIR /app
COPY requirements-monitoring.txt /app/requirements-monitoring.txt
RUN pip install --no-cache-dir -r /app/requirements-monitoring.txt

COPY . /app
ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1

CMD ["python", "run_monitoring_pipeline.py"]
